version: "3.13"

services:

  web:
    build: 
      context: .
    ports:
      - "8000:8000"
    command: ["sh", "./start.sh"]
    volumes:
      - .:/project-root
    env_file:
      - .env
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${name}
      - POSTGRES_USER=${user}
      - POSTGRES_PASSWORD=${password}

volumes:
  postgres_data: 